### ISSUE TITLE
Error loading the dataset

### ISSUE THREAD

**Issue by martinschorb** [mobie/hamburg-xray-datasets#1]
Hi @constantinpape , @tischi 

I get
```
Adding source: fibsem-raw...
[ERROR] Module threw exception
java.lang.NullPointerException
	at bdv.img.n5.N5GenericImageLoader.createSetupImgLoader(N5GenericImageLoader.java:166)
	at bdv.img.n5.N5GenericImageLoader.open(N5GenericImageLoader.java:114)
	at bdv.img.n5.N5GenericImageLoader.getSetupImgLoader(N5GenericImageLoader.java:158)
	at bdv.img.n5.N5GenericImageLoader.getSetupImgLoader(N5GenericImageLoader.java:75)
	at bdv.BigDataViewer.initSetupNumericType(BigDataViewer.java:260)
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:292)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:64)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:38)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:109)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:20)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:572)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.mobie.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:387)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:362)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:337)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:294)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:46)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:32)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:89)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:49)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:19)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

when I try to load the data from remote. 
Locally it works. The keys also work. (separate message)

Martin

**Comment by martinschorb** [comment]
switching to another dataset of the ones listed gives me:

```
Adding source: fibsem-raw...
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at bdv.img.n5.N5GenericImageLoader.createSetupImgLoader(N5GenericImageLoader.java:166)
	at bdv.img.n5.N5GenericImageLoader.open(N5GenericImageLoader.java:114)
	at bdv.img.n5.N5GenericImageLoader.getSetupImgLoader(N5GenericImageLoader.java:158)
	at bdv.img.n5.N5GenericImageLoader.getSetupImgLoader(N5GenericImageLoader.java:75)
	at bdv.BigDataViewer.initSetupNumericType(BigDataViewer.java:260)
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:292)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:64)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:38)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:109)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:20)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:572)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.mobie.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:387)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:362)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:337)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:294)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:46)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:32)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:89)
	at de.embl.cba.mobie.viewer.ActionPanel.switchDataset(ActionPanel.java:548)
	at de.embl.cba.mobie.viewer.ActionPanel.lambda$addDatasetSelectionUI$13(ActionPanel.java:536)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by martinschorb** [comment]
I get the same error as above when I try to load another of the datasets as default.

**Comment by constantinpape** [comment]
The issue is the `Key` field in the xml:
https://github.com/mobie/hamburg-xray-datasets/blob/master/data/TAH02/images/remote/fibsem-raw.xml#L28

It should be `data/TAH02/images/local/fibsem-raw.n5`.
I checked with the credentials you send me and `mc ls embl/xray-tomo/data/TAH02/images/local/fibsem-raw.n5` works whereas `embl/xray-tomo/TAH02/images/local/fibsem-raw.n5` fails.

**Comment by martinschorb** [comment]
hmm, OK.
Sure, that's where the data sits.
I had this in mind but then checked
https://github.com/mobie/covid-em-datasets/blob/master/data/Covid19-S4-Area1/images/remote/sbem-6dpf-1-whole-raw.xml#L29 where there's no `data` required.

Indeed, the difference is that for covid the datasets sit right at the top of the bucket whereas here, I have the additional data subdirectory in between. I will move the files in the bucket to stay consistent.

Thanks
